title: mori
description: "security researcher · day zero"
baseurl: ""
url: "https://mori0x0x.github.io"

collections:
  posts:
    output: true
    permalink: /posts/:slug/

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      visibility: private
      likes: 0

plugins:
  - jekyll-feed

markdown: kramdown
highlighter: rouge
